### ISSUE TITLE
Navbar SignUpPage Sizing

### ISSUE THREAD

**Issue by enbeatty** [SethBrittain/KSU-Conference-Planner#14]
Currently the signUpPage navbar is not properly size. This could be because of there being no buttons on the far right side of the navbar. Check the returns of the functions to see if it needs to change.

**Comment by SethBrittain** [comment]
Please see the tailwind rules I used here:
https://github.com/SethBrittain/KSU-Conference-Planner/blob/mui-to-tailwind/Frontend/src/Components/Navbars/Navbar.tsx
